# Generated by Django 3.0.7 on 2020-06-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerdetails',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='ipv4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='loopbackid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='sapid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='routerdetails',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
